apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./ingress.yaml
patchesStrategicMerge:
- ./deployment-patch.yaml
images:
- name: openzipkin
  newName: openzipkin/zipkin
  newTag: "2.23"
