apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector: 
    app.kubernetes.io/name: machina-postgres
    app.kubernetes.io/instance: database
  type: ClusterIP  
  ports:
    - port: 5432
      targetPort: 5432 
