apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-pvc
  labels:
    vol: postgres-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
